/******************************************************************************
* Descpription: Service Request Paramter information.
*/
public class ServiceRequestData {    
    public String accountId;
    public String dateSent;
    public String origin;
    public String subject;
    public String status;
    public String description;
    public string addressLine1;
    public string city;
    public string state;
    public string zip;
    public String srType;
}
